apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-chuck-job-jean
  namespace: $NAMESPACE
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-chuck-job-jean
        spec:
          restartPolicy: Never
          containers:
          - name: cron-chuck-job-jean
            image: jean1989/k8s-job-test:latest
            command: ["/var/app/job"]
            env:
            - name: SLACK_HOOK
              value: "${SLACK_HOOK}"
